icons_format = "{icon}"

[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#dbd9da"
idle_fg = "#3b4d4f"
info_bg = "#68c7c1"
info_fg = "#3b4d4f"
good_bg = "#a3be8c"
good_fg = "#3b4d4f"
warning_bg = "#d8af60"
warning_fg = "#3b4d4f"
critical_bg = "#e46c6d"
critical_fg = "#3b4d4f"
separator = " "
separator_bg = "none"

[icons]
icons = "material-nf"

[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
format = "  $icon $utilization.eng(w:2)  "

# [[block]]
# block = "disk_space"
# path = "/"
# info_type = "available"
# alert_unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = "  $icon $mem_used_percents.eng(w:2)  "
format_alt = "  $icon_swap $swap_used_percents.eng(w:2)  "

[[block]]
block = "sound"
format = "  $icon{ $volume|}  "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "  $timestamp.datetime(f:'%a %Y-%m-%d %R')  "
